/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafacturacionlibros;

import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author Arielo
 */
public class WindowLogin extends javax.swing.JFrame {

    Connection c = null;
    Statement stmt = null;
    Conexion miconexion = new Conexion();

    private VentanaPrincipal VPs;
    String loginuser;
    

    /**
     * Creates new form WindowLogin
     */
    public WindowLogin() {
        initComponents();
        loginuser = loginUser.toString();
        c = Conexion.dbConnector();
//        miconexion.CrearTablas();
//        miconexion.defaultAdmin();

    }

    public void CloseFrame() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginUsertxt = new javax.swing.JLabel();
        loginPasstxt = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        loginUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        imageBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginUsertxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        loginUsertxt.setText("Username");

        loginPasstxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        loginPasstxt.setText("Password");

        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/key.png"))); // NOI18N
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        loginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Introduzca sus datos para identificarse");

        imageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreria.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPasstxt)
                            .addComponent(loginUsertxt))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginPass, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(loginUser))
                        .addGap(74, 74, 74)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginUsertxt)
                            .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPasstxt)
                    .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(imageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        //Cuando el boton sea presionado
    //TODO
    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        //Login sencillo para usar hasta integrar login con base de datos
        //TODO
        checkIfUserPassExist();
// TODO add your handling code here:

    }//GEN-LAST:event_loginbtnActionPerformed

    private void loginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBook;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JLabel loginPasstxt;
    private static javax.swing.JTextField loginUser;
    private javax.swing.JLabel loginUsertxt;
    private javax.swing.JButton loginbtn;
    // End of variables declaration//GEN-END:variables

    public void checkIfUserPassExist() {
        try {
            String sql = "SELECT ID, Usuario, Password FROM Empleados WHERE Usuario=? AND Password=?";
            PreparedStatement pst = c.prepareStatement(sql);
            pst.setString(1, loginUser.getText());
            pst.setString(2, Arrays.toString(loginPass.getPassword()));
//            String passText = new String(loginPass.getPassword());
//            pst.setString(2, passText);
            ResultSet rs = pst.executeQuery();
            Conexion.setTextField(loginUser.getText());
            
//            String sqlUserID = "SELECT ID FROM Empleados WHERE Usuario=? AND Password=?";
//            pst = c.prepareStatement(sqlUserID);
//            pst.setString(1, loginUser.getText());
//            pst.setString(2, Arrays.toString(loginPass.getPassword()));
//            rs = pst.executeQuery();
         

            if (rs.isBeforeFirst()) {
                
                while(rs.next()){
                    int id = rs.getInt("ID");
                    Conexion.setUserID(id);
                }

                pst.close();
                rs.close();
                
                VentanaOpciones VO = new VentanaOpciones();
                VO.setVisible(true);
                VO.setTitle("Ventana Opciones");
                CloseFrame();
                
            } else {
                JOptionPane.showMessageDialog(null, "Dato equivocado");
                pst.close();
                rs.close();
            }
        } catch (SQLException | HeadlessException e) {
            System.out.println("checkIfUserPassExist " + e.getMessage());
        }
    }

}
